apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{SERVICE_NAME}}-secrets
  namespace: default
spec:
  encryptedData:
    # Add encrypted secrets here using kubeseal
  template:
    metadata:
      name: {{SERVICE_NAME}}-secrets
    type: Opaque
