# OPTIONAL: Sealed Secrets for {{SERVICE_NAME}}-stg
#
# This file is OPTIONAL. Only include this in kustomization.yaml if you have secrets to seal.
#
# When to use:
# - Database credentials
# - API keys
# - OAuth secrets
# - Any sensitive configuration
#
# When NOT to use:
# - Basic services with no sensitive data
# - Services using AWS Secrets Manager/Parameter Store exclusively
# - Public configuration
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{SERVICE_NAME}}-secrets
  namespace: default
spec:
  encryptedData:
    # Add encrypted secrets here using kubeseal
  template:
    metadata:
      name: {{SERVICE_NAME}}-secrets
    type: Opaque
