apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{SERVICE_NAME}}-{{ENVIRONMENT}}
  namespace: argocd
  labels:
    app: {{SERVICE_NAME}}
    environment: {{ENVIRONMENT}}
spec:
  project: default
  source:
    repoURL: https://github.com/BMJ-Ltd/{{REPOSITORY_NAME}}.git
    targetRevision: main
    path: {{SERVICE_NAME}}/overlays/{{ENVIRONMENT}}
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
