apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{SERVICE_NAME}}-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: {{STORAGE_SIZE}}
