apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    # IRSA role ARN - set in overlay via patch
    # eks.amazonaws.com/role-arn: arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/{{SERVICE_NAME}}-{{ENVIRONMENT}}-role
