apiVersion: v1
kind: Service
metadata:
  name: {{SERVICE_NAME}}
  annotations:
    # external-dns.alpha.kubernetes.io/hostname: {{SERVICE_NAME}}.ENV.eks.bmjgroup.com  # Set in service-patch.yaml
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{SERVICE_PORT}}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{SERVICE_NAME}}
